---

- hosts: junos
  remote_user: pi
  become: yes
  become_method: enable
  connection: netconf

  tasks:
  - name: Configure banner from file
    junos_banner:
      banner: login
      text: "{{ lookup('file', './raw_banner.cfg') }}"
      state: present

