---
- hosts: junos
  connection: netconf
  remote_user: root

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830  timeout=5

  - name: load configure file into device
    junos_config:
      src: srx.cfg
      comment: update config

