---
- hosts: junos
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830  timeout=5

  - name: show version
    junos_command:
      commands: show version
      display: json
    register: result

  - debug:
      var: result
