---
- hosts: junos
  remote_user: root
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830  timeout=5

  - name: run show version on remote devices
    junos_command:
      commands: show version
    register: version

  - debug: var=version.stdout_lines
