---
- hosts: junos
  remote_user: root

  tasks:
  - name: Configure banner from file
    junos_banner:
      banner: login
      text: "{{ lookup('file', './raw_banner.cfg') }}"
      state: present

